name: app-backend
version: 0.1.0.0
github: "juspay/atlas"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/atlas#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances

dependencies:
  - aeson
  - amazonka
  - amazonka-core
  - amazonka-ses
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - containers
  - cryptonite
  - euler-hs
  - http-api-data
  - http-client
  - http-types
  - lens
  - mtl
  - prometheus-client
  - wai-middleware-prometheus
  - prometheus-metrics-ghc
  - unliftio-core
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - text
  - wai
  - wai-extra
  - warp
  - time
  - random-strings
  - record-hasfield
  - record-dot-preprocessor
  - postgresql-simple
  - servant-openapi3
  - openapi3
  - persistent

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Werror
  dependencies:
    - atlas-core
executables:
  app-backend-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - app-backend
      - atlas-core
