name: mock-sms
version: 0.1.0.0
github: "juspay/atlas"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2020 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/atlas#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - euler-hs
  - record-hasfield
  - record-dot-preprocessor

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wunused-imports
  - -Werror
  - -fplugin=RecordDotPreprocessor

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns
  dependencies:
    - aeson
    - atlas-core
    - bytestring
    - clock
    - containers
    - http-types
    - servant-server
    - stm
    - text
    - time
    - time-units
    - wai
    - wai-extra
    - warp

executables:
  mock-sms-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
      - -Wincomplete-uni-patterns
    dependencies:
      - mock-sms
