name: example-service
version: 0.1.0.0
github: "juspay/atlas"
license: AllRightsReserved
author: "Juspay"
maintainer: "Juspay"
copyright: "2021 Juspay Technologies Private Limited"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://bitbucket.org/juspay/atlas#readme>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - atlas-core
  - bytestring
  - record-dot-preprocessor
  - record-hasfield
  - text
  - time
  - servant-server
  - persistent            
  - persistent-postgresql 
  - esqueleto           
  - template-haskell

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Widentities
  - -Wunused-imports
  - -fplugin=RecordDotPreprocessor
  - -fwrite-ide-info
  - -hiedir=.hie

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns

executables:
  example-service-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
      - -Wincomplete-uni-patterns
    dependencies:
      - example-service
      - atlas-core
